export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const MEDICINE_DATA = 'MEDICINE_DATA';
export const MEDICINE_LOADING = 'MEDICINE_LOADING';
export const MEDICINE_ERROR = 'MEDICINE_ERROR';
export const MEDICINE_ADD = 'MEDICINE_ADD';
export const MEDICINE_DELETE = 'MEDICINE_DELETE';
export const MEDICINE_UPDATE = 'MEDICINE_UPDATE';