export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const MEDICINE_DATA = 'MEDICINE_DATA';
export const MEDICINE_LOADING = 'MEDICINE_LOADING';
export const MEDICINE_ERROR = 'MEDICINE_ERROR';
export const MEDICINE_ADD = 'MEDICINE_ADD';
export const MEDICINE_DELETE = 'MEDICINE_DELETE';
export const MEDICINE_UPDATE = 'MEDICINE_UPDATE';

export const STAFF_DATA = "STAFF_DATA";
export const STAFF_ADD = "STAFF_ADD";
export const STAFF_LOADING = "STAFF_LOADING";
export const STAFF_ERROR = "STAFF_ERROR";
export const STAFF_DELETE = "STAFF_DELETE";
export const STAFF_UPDATE = "STAFF_UPDATE";

export const PATIENTS_ADD = "PATIENTS_ADD";
export const PATIENTS_DATA = "PATIENTS_DATA";